from django.urls import path,re_path
from . import views
from django.contrib.auth import views as auth_views
urlpatterns=[
	path('',views.index,name='index'),
	path('login/', auth_views.LoginView.as_view(template_name='Tronj/registration/login.html'), name="login"),
	path('login/forgot', views.forgot, name='forgot'),
	path('login/freset_password', views.freset_password, name='freset_password'),
	path('login/femail_verify',views.femail_verify,name='femail_verify'),
	path('login/ansbaseforgot',views.ansbaseforgot,name='ansbaseforgot'),
	path('login/femail_verify/Question_verify',views.Question_verify,name='Question_verify'),
	path('login/ansforgot',views.ansforgot,name='ansforgot'),
	path('login/ans_verify', views.ans_verify, name='ans_verify'),
	path('login/femail_verify/fConfirm', views.fConfirm, name='fConfirm'),
	path('login/fConfirm', views.fConfirm, name='fConfirm'),
	path('login/email_confirm', views.email_confirm, name='email_confirm'),
	path('logout/', auth_views.LogoutView.as_view(template_name='Tronj/logout.html'),name='logout'),
	path('myAccount/logout/', auth_views.LogoutView.as_view(template_name='index.html'),name='logout'),
	path('myAccount/Empeditpre/', views.Empeditpre,name='Empeditpre'),
	path('register/',views.register,name='register'),
	path('register/Company',views.Com_signup,name='Com_signup'),
	path('myAccount/',views.myAccount,name='myAccount'),

	path('myAccount/edit_Profile', views.edit_Profile, name='edit_Profile'),
	path('myAccount/edit',views.edit,name='edit'),
	path('myAccount/Exprience',views.Expre_Content,name='Expre_Content'),
	path('myAccount/Education',views.Edu_Content,name='Edu_Content'),
	path('myAccount/email_verify/resetquestion',views.resetquestion,name='resetquestion'),
	path('myAccount/email_verify',views.email_verify,name='email_verify'),
	path('myAccount/email_confirm', views.email_confirm, name='email_confirm'),
	path('myAccount/Confirm', views.Confirm, name='Confirm'),
path('myAccount/authen_email_confirm/Confirm', views.Confirm, name='Confirm'),

	path('to_apply/',views.to_apply,name='to_apply'),
	path('to_apply/joboffered',views.joboffered,name='joboffered'),
	path('signin',views.signin,name='signin'),
	path('myAccount/Cappli_review',views.Cappli_review,name='Cappli_review'),


	path('skilltest/',views.skill_test,name='skill_test'),
	path('skilltest/round1',views.round1,name='round1'),
	path('skilltest/round2',views.round2,name='round2'),
	path('customerMain/',views.customerMain,name='customerMain'),
	path('myAccount/Cappli_review/(?P <id>[\W-]+)',views.appli_info,name='appli_info'),
	path('myAccount/Cappli_review/(?P <id>[\W-]+)/updatee',views.updatee,name='updatee'),
	path('myAccount/Cappli_review/updatee',views.updatee,name='updatee'),
	path('apply/(?P <id>[\W-]+)',views.info,name='info'),
	path('apply/sub',views.sub,name='sub'),
	path('skilltest/result/',views.result,name='result'),
	path('myAccount/company_form/',views.company_form,name='company_form'),
	path('myAccount/eduedit/',views.eduedit,name='eduedit'),
	path('myAccount/authen_email_confirm/',views.authen_email_confirm,name='authen_email_confirm'),
	path('myAccount/Exp_edit/',views.Exp_edit,name='Exp_edit'),
	path('myAccount/comeditpre/',views.comeditpre,name='comeditpre'),
	path('myAccount/email_verify/QA_Check/',views.QA_Check,name='QA_Check'),
path('myAccount/email_verify/QA_set/',views.QA_set,name='QA_set'),
	path('myAccount/email_verify/QA_Check/Confirm/',views.Confirm,name='Confirm'),
	path('myAccount/Capplication/',views.Capplication,name='Capplication'),
	path('myAccount/Capplication/(?P <id>[\W-]+)',views.posted_job,name='posted_job'),
	path('myAccount/Capplication/(?P <id>[\W-]+)/posted_job_update',views.posted_job_update,name='posted_job_update'),
	path('myAccount/Eapplication/',views.Eapplication,name='Eapplication'),
]
