# Generated by Django 2.2.3 on 2019-12-27 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(default='', max_length=50)),
                ('Location', models.CharField(default='', max_length=50)),
                ('stipend', models.IntegerField(default=0)),
                ('Skills_Required', models.CharField(default='', max_length=50)),
                ('Job_timings', models.IntegerField(default=0)),
                ('Start_of_intern', models.IntegerField(default=0)),
                ('CEmail', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='fresher_Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Date_of_birth', models.DateField(verbose_name='Date')),
                ('Address', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=50)),
                ('SSLC', models.IntegerField()),
                ('PUC', models.IntegerField()),
                ('Graduation', models.IntegerField()),
                ('Phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='skilltest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.IntegerField()),
                ('cloud', models.IntegerField()),
                ('web', models.IntegerField()),
                ('C', models.IntegerField()),
                ('Cadvance', models.IntegerField()),
                ('java', models.IntegerField()),
                ('netframe', models.IntegerField()),
                ('php', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
