# Generated by Django 2.2.3 on 2019-12-29 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresher_profile',
            name='C',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fresher_profile',
            name='Cadvance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fresher_profile',
            name='cloud',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fresher_profile',
            name='java',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fresher_profile',
            name='netframe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fresher_profile',
            name='php',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fresher_profile',
            name='python',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fresher_profile',
            name='web',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fresher_profile',
            name='Date_of_birth',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='fresher_profile',
            name='Graduation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fresher_profile',
            name='PUC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fresher_profile',
            name='Phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fresher_profile',
            name='SSLC',
            field=models.IntegerField(default=0),
        ),
    ]
