# Generated by Django 2.2.3 on 2019-12-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0002_auto_20191229_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=50)),
                ('Fresher', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
