# Generated by Django 2.2.3 on 2019-12-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0003_applications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fresher_profile',
            old_name='cloud',
            new_name='Cloud',
        ),
        migrations.RenameField(
            model_name='fresher_profile',
            old_name='php',
            new_name='PHP',
        ),
    ]
