# Generated by Django 2.2.3 on 2020-01-03 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0004_auto_20191229_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='Start_of_intern',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
