# Generated by Django 2.2.3 on 2020-01-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0005_auto_20200103_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='Job_timings',
            field=models.CharField(default='', max_length=50),
        ),
    ]
