# Generated by Django 2.2.3 on 2020-01-12 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0007_fresher_profile_postgraduation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avilable_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('stipend', models.IntegerField(default=0)),
                ('Skills_Required', models.CharField(default='', max_length=50)),
                ('Job_timings', models.CharField(default='', max_length=50)),
                ('Start_of_intern', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('CEmail', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='Job_timings',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='company_details',
            name='C',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='Cadvance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='Cloud',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='Date_posted',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='company_details',
            name='Graduation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='Job_timings_end',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company_details',
            name='Job_timings_start',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company_details',
            name='PHP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='PUC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='PostGraduation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='SSLC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company_details',
            name='experienced_programming_langauage',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company_details',
            name='java',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='jobdescription',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='company_details',
            name='netframe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='python',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='web',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_details',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fresher_profile',
            name='Location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fresher_profile',
            name='experienced_programming_langauage',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='fresher_profile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
