# Generated by Django 2.2.3 on 2020-01-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0008_auto_20200112_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='avilable_work',
            name='Employee',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='avilable_work',
            name='Employee_email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
