# Generated by Django 2.2.3 on 2020-01-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0009_auto_20200127_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avilable_work',
            name='Job_timings',
        ),
    ]
