# Generated by Django 2.2.3 on 2020-02-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0010_remove_avilable_work_job_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='avilable_work',
            name='Answer1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='avilable_work',
            name='Answer2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='avilable_work',
            name='Answer3',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='avilable_work',
            name='Question1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='avilable_work',
            name='Question2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='avilable_work',
            name='Question3',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company_details',
            name='Question1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company_details',
            name='Question2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company_details',
            name='Question3',
            field=models.CharField(default='', max_length=150),
        ),
    ]
