# Generated by Django 2.2.3 on 2020-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0011_auto_20200202_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avilable_work',
            name='Answer1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='Answer2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='Answer3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='CEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='Employee',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='Employee_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='Question1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='Question2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='Question3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='Skills_Required',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avilable_work',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
