# Generated by Django 2.2.3 on 2020-02-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0013_auto_20200202_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='Question1',
            field=models.CharField(default='Why you want this Job?', max_length=150),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='Question2',
            field=models.CharField(default='Why should we give you this job?', max_length=150),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='Question3',
            field=models.CharField(default='What are your strength and weakness?', max_length=150),
        ),
    ]
