# Generated by Django 2.2.3 on 2020-02-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0014_auto_20200204_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresher_profile',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
