# Generated by Django 2.2.3 on 2020-02-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0015_fresher_profile_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='Address',
        ),
    ]
