# Generated by Django 2.2.3 on 2020-02-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0016_remove_company_details_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avilable_work',
            name='Start_of_intern',
        ),
    ]
