# Generated by Django 2.2.3 on 2020-02-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0017_remove_avilable_work_start_of_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='avilable_work',
            name='offer_id',
            field=models.IntegerField(default=0),
        ),
    ]
