# Generated by Django 2.2.3 on 2020-03-03 17:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Tronj', '0018_avilable_work_offer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Father_Name', models.CharField(default='', max_length=150)),
                ('Date_of_birth', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('Address', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=50)),
                ('State', models.CharField(default='', max_length=50)),
                ('Postal_code', models.IntegerField(default=0)),
                ('SSLC', models.IntegerField(default=0)),
                ('SSLC_name', models.CharField(default='', max_length=150)),
                ('SSLC_board', models.CharField(default='', max_length=150)),
                ('SSLC_Percentage', models.IntegerField(default=0)),
                ('SSLC_passed_year', models.IntegerField(default=0)),
                ('PUC', models.IntegerField(default=0)),
                ('PUC_name', models.CharField(default='', max_length=150)),
                ('PUC_board', models.CharField(default='', max_length=150)),
                ('PUC_Percentage', models.IntegerField(default=0)),
                ('PUC_passed_year', models.IntegerField(default=0)),
                ('Graduation', models.IntegerField(default=0)),
                ('Graduation_name', models.CharField(default='', max_length=150)),
                ('Graduation_board', models.CharField(default='', max_length=150)),
                ('Graduation_Percentage', models.IntegerField(default=0)),
                ('Graduation_passed_year', models.IntegerField(default=0)),
                ('PostGraduation', models.IntegerField(default=0)),
                ('PostGraduation_name', models.CharField(default='', max_length=150)),
                ('PostGraduation_board', models.CharField(default='', max_length=150)),
                ('PostGraduation_Percentage', models.IntegerField(default=0)),
                ('PostGraduation_passed_year', models.IntegerField(default=0)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('experienced_programming_langauage', models.CharField(default='', max_length=150)),
                ('experienced_Company_name', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
