# Generated by Django 2.2.3 on 2020-03-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0019_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='C',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='Cadvance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='Cloud',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='PHP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='java',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='netframe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='web',
            field=models.IntegerField(default=0),
        ),
    ]
