# Generated by Django 2.2.3 on 2020-03-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0020_auto_20200303_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Graduation',
            new_name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PUC',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='SSLC',
        ),
    ]
