# Generated by Django 2.2.3 on 2020-03-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0021_auto_20200304_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresher_profile',
            name='exp_Company_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
