# Generated by Django 2.2.3 on 2020-03-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0022_fresher_profile_exp_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fresher_profile',
            name='exp_Company_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='Graduation_IN',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='PUC_IN',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='PostGraduation_IN',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='exp_Company_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
