# Generated by Django 2.2.3 on 2020-03-06 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Tronj', '0023_auto_20200305_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Address', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=50)),
                ('State', models.CharField(default='', max_length=50)),
                ('Postal_code', models.IntegerField(default=0)),
                ('Phone_number', models.IntegerField(default=0)),
                ('python', models.IntegerField(default=0)),
                ('Cloud', models.IntegerField(default=0)),
                ('web', models.IntegerField(default=0)),
                ('C', models.IntegerField(default=0)),
                ('Cadvance', models.IntegerField(default=0)),
                ('java', models.IntegerField(default=0)),
                ('netframe', models.IntegerField(default=0)),
                ('PHP', models.IntegerField(default=0)),
                ('pincode', models.IntegerField(default=0)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('experienced_programming_langauage', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
