# Generated by Django 2.2.3 on 2020-03-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0024_company_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='Graduation',
        ),
        migrations.RemoveField(
            model_name='company_details',
            name='PUC',
        ),
        migrations.RemoveField(
            model_name='company_details',
            name='PostGraduation',
        ),
        migrations.RemoveField(
            model_name='company_details',
            name='SSLC',
        ),
    ]
