# Generated by Django 2.2.3 on 2020-03-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0026_employee_python'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_profile',
            name='pincode',
        ),
    ]
