# Generated by Django 2.2.3 on 2020-03-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0027_remove_company_profile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_profile',
            name='about_company',
            field=models.CharField(default='', max_length=1150),
        ),
    ]
