# Generated by Django 2.2.3 on 2020-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0028_company_profile_about_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Communication_lng',
            field=models.CharField(default='', max_length=50),
        ),
    ]
