# Generated by Django 2.2.3 on 2020-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0029_employee_communication_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Marriage_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
