# Generated by Django 2.2.3 on 2020-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0030_employee_marriage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Strength',
            field=models.CharField(default='', max_length=50),
        ),
    ]
