# Generated by Django 2.2.3 on 2020-03-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0031_employee_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Carrer_Objective',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Communication_lng',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Strength',
            field=models.CharField(default='', max_length=500),
        ),
    ]
