# Generated by Django 2.2.3 on 2020-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0032_auto_20200310_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_profile',
            name='A1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company_profile',
            name='A2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company_profile',
            name='Q1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company_profile',
            name='Q2',
            field=models.CharField(default='', max_length=150),
        ),
    ]
