# Generated by Django 2.2.3 on 2020-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0033_auto_20200311_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='A1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='A2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='Q1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='Q2',
            field=models.CharField(default='', max_length=150),
        ),
    ]
