# Generated by Django 2.2.3 on 2020-03-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0034_auto_20200311_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_details',
            old_name='Cloud',
            new_name='Csharp',
        ),
        migrations.RenameField(
            model_name='company_profile',
            old_name='Cloud',
            new_name='Csharp',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Cloud',
            new_name='Csharp',
        ),
        migrations.RenameField(
            model_name='fresher_profile',
            old_name='Cloud',
            new_name='Csharp',
        ),
    ]
