# Generated by Django 2.2.3 on 2020-03-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0039_company_details_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='job_type',
            field=models.CharField(default='internship', max_length=50),
        ),
    ]
