# Generated by Django 2.2.3 on 2020-03-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0041_company_details_about_the_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_profile',
            name='C',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='Cadvance',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='Csharp',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='PHP',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='experienced_programming_langauage',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='java',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='netframe',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='python',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='web',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='years_of_experience',
        ),
    ]
