# Generated by Django 2.2.3 on 2020-04-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0042_auto_20200331_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSLC_name', models.CharField(default='', max_length=150)),
                ('SSLC_board', models.CharField(default='', max_length=150)),
                ('SSLC_Percentage', models.IntegerField(default=0)),
                ('SSLC_passed_year', models.IntegerField(default=0)),
                ('PUC_IN', models.CharField(default='', max_length=150)),
                ('PUC_name', models.CharField(default='', max_length=150)),
                ('PUC_board', models.CharField(default='', max_length=150)),
                ('PUC_Percentage', models.IntegerField(default=0)),
                ('PUC_passed_year', models.IntegerField(default=0)),
                ('Graduation_IN', models.CharField(default='', max_length=150)),
                ('Graduation_name', models.CharField(default='', max_length=150)),
                ('Graduation_board', models.CharField(default='', max_length=150)),
                ('Graduation_Percentage', models.IntegerField(default=0)),
                ('Graduation_passed_year', models.IntegerField(default=0)),
                ('PostGraduation_IN', models.CharField(default='', max_length=150)),
                ('PostGraduation', models.IntegerField(default=0)),
                ('PostGraduation_name', models.CharField(default='', max_length=150)),
                ('PostGraduation_board', models.CharField(default='', max_length=150)),
                ('PostGraduation_Percentage', models.IntegerField(default=0)),
                ('PostGraduation_passed_year', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Graduation_IN',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Graduation_Percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Graduation_board',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Graduation_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Graduation_passed_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PUC_IN',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PUC_Percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PUC_board',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PUC_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PUC_passed_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PostGraduation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PostGraduation_IN',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PostGraduation_Percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PostGraduation_board',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PostGraduation_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PostGraduation_passed_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='SSLC_Percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='SSLC_board',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='SSLC_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='SSLC_passed_year',
        ),
    ]
