# Generated by Django 2.2.3 on 2020-04-02 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tronj', '0043_auto_20200403_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='C',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Cadvance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Csharp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='PHP',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='java',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='netframe',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='python',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='web',
        ),
        migrations.RemoveField(
            model_name='skilltest',
            name='cloud',
        ),
        migrations.RemoveField(
            model_name='skilltest',
            name='php',
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilltest',
            name='Csharp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='PHP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='C',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='Cadvance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='java',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='netframe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='python',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='web',
            field=models.IntegerField(default=0),
        ),
    ]
