# Generated by Django 2.2.3 on 2020-04-02 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0044_auto_20200403_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltest',
            name='C_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='C_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='Cadvance_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='Cadvance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='Csharp_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='Csharp_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='PHP_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='PHP_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='java_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='java_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='netframe_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='netframe_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='python_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='python_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='web_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='web_count',
            field=models.IntegerField(default=0),
        ),
    ]
