# Generated by Django 2.2.3 on 2020-04-02 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tronj', '0045_auto_20200403_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltest',
            name='id',
        ),
        migrations.AddField(
            model_name='skilltest',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
