# Generated by Django 2.2.3 on 2020-04-02 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Tronj', '0046_auto_20200403_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_Education',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('SSLC_name', models.CharField(default='', max_length=150)),
                ('SSLC_board', models.CharField(default='', max_length=150)),
                ('SSLC_Percentage', models.IntegerField(default=0)),
                ('SSLC_passed_year', models.IntegerField(default=0)),
                ('PUC_IN', models.CharField(default='', max_length=150)),
                ('PUC_name', models.CharField(default='', max_length=150)),
                ('PUC_board', models.CharField(default='', max_length=150)),
                ('PUC_Percentage', models.IntegerField(default=0)),
                ('PUC_passed_year', models.IntegerField(default=0)),
                ('Graduation_IN', models.CharField(default='', max_length=150)),
                ('Graduation_name', models.CharField(default='', max_length=150)),
                ('Graduation_board', models.CharField(default='', max_length=150)),
                ('Graduation_Percentage', models.IntegerField(default=0)),
                ('Graduation_passed_year', models.IntegerField(default=0)),
                ('PostGraduation_IN', models.CharField(default='', max_length=150)),
                ('PostGraduation', models.IntegerField(default=0)),
                ('PostGraduation_name', models.CharField(default='', max_length=150)),
                ('PostGraduation_board', models.CharField(default='', max_length=150)),
                ('PostGraduation_Percentage', models.IntegerField(default=0)),
                ('PostGraduation_passed_year', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='education',
        ),
    ]
