# Generated by Django 2.2.3 on 2020-04-06 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0047_auto_20200403_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltest',
            name='Csharp_Date',
            field=models.DateField(default=datetime.date(2020, 1, 20), verbose_name='Date'),
        ),
    ]
