# Generated by Django 2.2.3 on 2020-04-06 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tronj', '0049_auto_20200406_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltest',
            name='Cadvance_Date',
            field=models.DateField(default=datetime.date(2020, 1, 20), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='PHP_Date',
            field=models.DateField(default=datetime.date(2020, 1, 20), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='java_Date',
            field=models.DateField(default=datetime.date(2020, 1, 20), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='netframe_Date',
            field=models.DateField(default=datetime.date(2020, 1, 20), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='python_Date',
            field=models.DateField(default=datetime.date(2020, 1, 20), verbose_name='Date'),
        ),
    ]
